/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Framesregis;
import ArrayList.HSucursalesArray;
import ArrayList.HSucursalesProvinciaArray;
import Clases.HSucursalesProvincia;
import Clases.HSucursales;
import conexionbd.Conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author USER
 */
public class FrameSucursales extends javax.swing.JFrame {
    DefaultTableModel tprincipal = new DefaultTableModel();
    DefaultTableModel tprovincia = new DefaultTableModel();
    HSucursalesArray hSucursalesArray = new HSucursalesArray();
    HSucursalesProvinciaArray hspa = new HSucursalesProvinciaArray();
    Conexion db= new Conexion();
    Connection cn=  db.conectar();
    
    /**
     * Creates new form sucursales
     */
    public FrameSucursales() {
        initComponents();
        setLocationRelativeTo(null);
        db.conectar();
        mostrartablaprin();
        mostrartablaprovin();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JtabbedPane = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jlabelnumsucursal = new javax.swing.JLabel();
        jlabelnomEncargado = new javax.swing.JLabel();
        jlabeldni = new javax.swing.JLabel();
        jlabeltelf = new javax.swing.JLabel();
        jlabelciudad = new javax.swing.JLabel();
        jlabeldireccion = new javax.swing.JLabel();
        txtnumsuc = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtdni = new javax.swing.JTextField();
        txttelf = new javax.swing.JTextField();
        txtciudad = new javax.swing.JTextField();
        txtdire = new javax.swing.JTextField();
        botonIngr = new javax.swing.JButton();
        botonLim = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblprincipal = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        numSucursalProv = new javax.swing.JLabel();
        numEncargProv = new javax.swing.JLabel();
        dniProv = new javax.swing.JLabel();
        telefonoProv = new javax.swing.JLabel();
        ciudadProv = new javax.swing.JLabel();
        direccionProv = new javax.swing.JLabel();
        txtnumsuc2 = new javax.swing.JTextField();
        txtnombreenc2 = new javax.swing.JTextField();
        txtdni2 = new javax.swing.JTextField();
        txttelef2 = new javax.swing.JTextField();
        txtciudad2 = new javax.swing.JTextField();
        txtdirec2 = new javax.swing.JTextField();
        botonIngProv = new javax.swing.JButton();
        botonLimProv = new javax.swing.JButton();
        provincia = new javax.swing.JLabel();
        codProv = new javax.swing.JLabel();
        txtprovi2 = new javax.swing.JTextField();
        txtcodprovi2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblprovin = new javax.swing.JTable();
        jTextField2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JtabbedPane.setBackground(new java.awt.Color(204, 255, 255));
        JtabbedPane.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JtabbedPane.setForeground(new java.awt.Color(7, 62, 91));
        JtabbedPane.setToolTipText("");
        JtabbedPane.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        JtabbedPane.setName(""); // NOI18N

        jPanel4.setBackground(new java.awt.Color(153, 217, 234));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlabelnumsucursal.setBackground(new java.awt.Color(0, 0, 0));
        jlabelnumsucursal.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jlabelnumsucursal.setForeground(new java.awt.Color(0, 0, 0));
        jlabelnumsucursal.setText("Número Sucursal :");
        jPanel4.add(jlabelnumsucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 130, 20));

        jlabelnomEncargado.setBackground(new java.awt.Color(0, 0, 0));
        jlabelnomEncargado.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jlabelnomEncargado.setForeground(new java.awt.Color(0, 0, 0));
        jlabelnomEncargado.setText("Nombre del encargado :");
        jPanel4.add(jlabelnomEncargado, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 157, -1, -1));

        jlabeldni.setBackground(new java.awt.Color(0, 0, 0));
        jlabeldni.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jlabeldni.setForeground(new java.awt.Color(0, 0, 0));
        jlabeldni.setText("DNI :");
        jPanel4.add(jlabeldni, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 160, -1, 20));

        jlabeltelf.setBackground(new java.awt.Color(0, 0, 0));
        jlabeltelf.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jlabeltelf.setForeground(new java.awt.Color(0, 0, 0));
        jlabeltelf.setText("Telefono :");
        jPanel4.add(jlabeltelf, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 80, 70, 22));

        jlabelciudad.setBackground(new java.awt.Color(0, 0, 0));
        jlabelciudad.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jlabelciudad.setForeground(new java.awt.Color(0, 0, 0));
        jlabelciudad.setText("Ciudad :");
        jPanel4.add(jlabelciudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 60, 20));

        jlabeldireccion.setBackground(new java.awt.Color(0, 0, 0));
        jlabeldireccion.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jlabeldireccion.setForeground(new java.awt.Color(0, 0, 0));
        jlabeldireccion.setText("Dirección :");
        jPanel4.add(jlabeldireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, 80, -1));

        txtnumsuc.setBackground(new java.awt.Color(246, 241, 241));
        txtnumsuc.setForeground(new java.awt.Color(0, 0, 0));
        txtnumsuc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnumsucKeyTyped(evt);
            }
        });
        jPanel4.add(txtnumsuc, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 194, -1));

        txtNombre.setBackground(new java.awt.Color(246, 241, 241));
        txtNombre.setForeground(new java.awt.Color(0, 0, 0));
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });
        jPanel4.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 194, -1));

        txtdni.setBackground(new java.awt.Color(246, 241, 241));
        txtdni.setForeground(new java.awt.Color(0, 0, 0));
        txtdni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtdniKeyTyped(evt);
            }
        });
        jPanel4.add(txtdni, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 160, 194, -1));

        txttelf.setBackground(new java.awt.Color(246, 241, 241));
        txttelf.setForeground(new java.awt.Color(0, 0, 0));
        txttelf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttelfActionPerformed(evt);
            }
        });
        txttelf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txttelfKeyTyped(evt);
            }
        });
        jPanel4.add(txttelf, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 80, 194, -1));

        txtciudad.setBackground(new java.awt.Color(246, 241, 241));
        txtciudad.setForeground(new java.awt.Color(0, 0, 0));
        txtciudad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtciudadKeyTyped(evt);
            }
        });
        jPanel4.add(txtciudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 194, -1));

        txtdire.setBackground(new java.awt.Color(246, 241, 241));
        txtdire.setForeground(new java.awt.Color(0, 0, 0));
        jPanel4.add(txtdire, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 120, 194, -1));

        botonIngr.setBackground(new java.awt.Color(25, 140, 255));
        botonIngr.setForeground(new java.awt.Color(0, 0, 0));
        botonIngr.setText("AGREGAR");
        botonIngr.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonIngr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIngrActionPerformed(evt);
            }
        });
        jPanel4.add(botonIngr, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, -1, 41));

        botonLim.setBackground(new java.awt.Color(255, 255, 255));
        botonLim.setForeground(new java.awt.Color(0, 0, 0));
        botonLim.setText("LIMPIAR");
        botonLim.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonLim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLimActionPerformed(evt);
            }
        });
        jPanel4.add(botonLim, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 450, -1, 41));

        jButton1.setBackground(new java.awt.Color(204, 0, 0));
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("VOLVER");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 450, -1, 41));

        tblprincipal.setBackground(new java.awt.Color(246, 241, 241));
        tblprincipal.setForeground(new java.awt.Color(0, 0, 0));
        tblprincipal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numero Sucursal", "Telefono", "Ciudad", "Direccion", "Encargado", "DNI"
            }
        ));
        jScrollPane3.setViewportView(tblprincipal);

        jPanel4.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 810, 230));

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(7, 62, 91));
        jTextField1.setFont(new java.awt.Font("Stencil", 2, 36)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(246, 241, 241));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("REGISTROS DE SUCURSALES DE LIMA");
        jPanel4.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 862, 61));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 517, Short.MAX_VALUE)
        );

        JtabbedPane.addTab("Principal", jPanel2);

        jPanel3.setBackground(new java.awt.Color(153, 217, 234));
        jPanel3.setForeground(new java.awt.Color(204, 204, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        numSucursalProv.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        numSucursalProv.setForeground(new java.awt.Color(0, 0, 0));
        numSucursalProv.setText("Número Sucursal:");
        jPanel3.add(numSucursalProv, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 130, 20));

        numEncargProv.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        numEncargProv.setForeground(new java.awt.Color(0, 0, 0));
        numEncargProv.setText("Nombre del encargado:");
        jPanel3.add(numEncargProv, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, -1, 20));

        dniProv.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        dniProv.setForeground(new java.awt.Color(0, 0, 0));
        dniProv.setText("DNI:");
        jPanel3.add(dniProv, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 190, -1, 28));

        telefonoProv.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        telefonoProv.setForeground(new java.awt.Color(0, 0, 0));
        telefonoProv.setText("Telefono:");
        jPanel3.add(telefonoProv, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, -1, 20));

        ciudadProv.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        ciudadProv.setForeground(new java.awt.Color(0, 0, 0));
        ciudadProv.setText("Ciudad:");
        jPanel3.add(ciudadProv, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, -1, 20));

        direccionProv.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        direccionProv.setForeground(new java.awt.Color(0, 0, 0));
        direccionProv.setText("Dirección:");
        jPanel3.add(direccionProv, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, -1, 20));

        txtnumsuc2.setBackground(new java.awt.Color(246, 241, 241));
        txtnumsuc2.setForeground(new java.awt.Color(0, 0, 0));
        txtnumsuc2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnumsuc2ActionPerformed(evt);
            }
        });
        txtnumsuc2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnumsuc2KeyTyped(evt);
            }
        });
        jPanel3.add(txtnumsuc2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 160, -1));

        txtnombreenc2.setBackground(new java.awt.Color(246, 241, 241));
        txtnombreenc2.setForeground(new java.awt.Color(0, 0, 0));
        txtnombreenc2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombreenc2ActionPerformed(evt);
            }
        });
        txtnombreenc2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnombreenc2KeyTyped(evt);
            }
        });
        jPanel3.add(txtnombreenc2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 160, -1));

        txtdni2.setBackground(new java.awt.Color(246, 241, 241));
        txtdni2.setForeground(new java.awt.Color(0, 0, 0));
        txtdni2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtdni2KeyTyped(evt);
            }
        });
        jPanel3.add(txtdni2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 200, 190, -1));

        txttelef2.setBackground(new java.awt.Color(246, 241, 241));
        txttelef2.setForeground(new java.awt.Color(0, 0, 0));
        txttelef2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttelef2ActionPerformed(evt);
            }
        });
        txttelef2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txttelef2KeyTyped(evt);
            }
        });
        jPanel3.add(txttelef2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 80, 190, -1));

        txtciudad2.setBackground(new java.awt.Color(246, 241, 241));
        txtciudad2.setForeground(new java.awt.Color(0, 0, 0));
        txtciudad2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtciudad2KeyTyped(evt);
            }
        });
        jPanel3.add(txtciudad2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 160, -1));

        txtdirec2.setBackground(new java.awt.Color(246, 241, 241));
        txtdirec2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(txtdirec2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 160, 190, -1));

        botonIngProv.setBackground(new java.awt.Color(25, 140, 255));
        botonIngProv.setForeground(new java.awt.Color(0, 0, 0));
        botonIngProv.setText("AGREGAR");
        botonIngProv.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonIngProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIngProvActionPerformed(evt);
            }
        });
        jPanel3.add(botonIngProv, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, -1, 41));

        botonLimProv.setBackground(new java.awt.Color(255, 255, 255));
        botonLimProv.setForeground(new java.awt.Color(0, 0, 0));
        botonLimProv.setText("LIMPIAR");
        botonLimProv.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonLimProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLimProvActionPerformed(evt);
            }
        });
        jPanel3.add(botonLimProv, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 430, -1, 41));

        provincia.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        provincia.setForeground(new java.awt.Color(0, 0, 0));
        provincia.setText("Provincia:");
        jPanel3.add(provincia, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, -1, 20));

        codProv.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        codProv.setForeground(new java.awt.Color(0, 0, 0));
        codProv.setText("Código de Provincia:");
        jPanel3.add(codProv, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, -1, 20));

        txtprovi2.setBackground(new java.awt.Color(246, 241, 241));
        txtprovi2.setForeground(new java.awt.Color(0, 0, 0));
        txtprovi2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprovi2ActionPerformed(evt);
            }
        });
        txtprovi2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtprovi2KeyTyped(evt);
            }
        });
        jPanel3.add(txtprovi2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 120, 190, 24));

        txtcodprovi2.setBackground(new java.awt.Color(246, 241, 241));
        txtcodprovi2.setForeground(new java.awt.Color(0, 0, 0));
        txtcodprovi2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcodprovi2KeyTyped(evt);
            }
        });
        jPanel3.add(txtcodprovi2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 160, -1));

        jButton2.setBackground(new java.awt.Color(255, 0, 51));
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("VOLVER");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 430, -1, 41));

        tblprovin.setBackground(new java.awt.Color(246, 241, 241));
        tblprovin.setForeground(new java.awt.Color(0, 0, 0));
        tblprovin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numero Sucursal", "Telefono", "Cod. Provincia", "Provincia", "Ciudad", "Direccion", "Encargado", "DNI"
            }
        ));
        jScrollPane2.setViewportView(tblprovin);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 240, 800, 171));

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(7, 62, 91));
        jTextField2.setFont(new java.awt.Font("Stencil", 2, 36)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(246, 241, 241));
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("REGISTROS DE SUCURSALES DE PROVINCIAS");
        jPanel3.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 862, 60));

        JtabbedPane.addTab("Provincia", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JtabbedPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JtabbedPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txttelfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttelfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttelfActionPerformed
    
    public void mostrartablaprin(){
        
        tprincipal = new DefaultTableModel();
        tprincipal.addColumn("Numero de sucursal");
        tprincipal.addColumn("Teléfono");
        tprincipal.addColumn("Ciudad");
        tprincipal.addColumn("Dirección");
        tprincipal.addColumn("Encargado");
        tprincipal.addColumn("DNI");
        tblprincipal.setModel(tprincipal);
        
        String sql="Select * From sucursalpri";
        String datos [] = new String [6];
        Statement st;
        
        try{
            st= cn.createStatement();
            ResultSet rs=st.executeQuery(sql);
            while(rs.next()){
                
                datos[0]=rs.getString(1);
                datos[1]=rs.getString(2);
                datos[2]=rs.getString(3);
                datos[3]=rs.getString(4);
                datos[4]=rs.getString(5);
                datos[5]=rs.getString(6);
                
                tprincipal.addRow(datos);
            }
            tblprincipal.setModel(tprincipal);
        }catch(SQLException ex){
            Logger.getLogger(FrameProductos.class.getName()).log(Level.SEVERE,null,ex);
        }
        
    }
    
    
    private void botonIngrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIngrActionPerformed
        // TODO add your handling code here:
      int Sucursal = 0;
      int dni = 0;
      int telefono = 0;
      boolean datosValidos = true;
      
       if(txtnumsuc.getText().isEmpty() || txtNombre.getText().isEmpty()|| txtdni.getText().isEmpty()||txttelf.getText().isEmpty()|| txtciudad.getText().isEmpty() || txtdire.getText().isEmpty() ) {     
       JOptionPane.showMessageDialog(null, "Complete los campos");
       datosValidos = false;}
       else{ 
           
       String nombre= txtNombre.getText();
       if (!validarLetras(txtNombre.getText())) 
       {JOptionPane.showMessageDialog(null, "Error al ingresar dato NOMBRE DEL ENCARGADO");
       datosValidos = false;}
       
       String distrito =txtciudad.getText();
       if (!validarLetras(txtciudad.getText())) 
       {JOptionPane.showMessageDialog(null, "Error al ingresar dato DISTRITO");
       datosValidos = false;}
       
       String direcc =txtdire.getText();
       
       try {
        dni = Integer.parseInt(txtdni.getText());
        if (txtdni.getText().length() != 8) {
        JOptionPane.showMessageDialog(null, "El DNI debe tener 8 dígitos");
        datosValidos = false; // Marcar los datos como no válidos
        } else {
        dni = Integer.parseInt(txtdni.getText());
        }
        } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Ingrese un número válido para DNI");
        datosValidos = false; // Marcar los datos como no válidos
        }

       
        try {
        Sucursal=Integer.parseInt(txtnumsuc.getText());
        if (txtnumsuc.getText().length() != 5) {
        JOptionPane.showMessageDialog(null, "El N° SUCURSAL debe tener 5 dígitos");
        datosValidos = false; // Marcar los datos como no válidos
        } else {
        Sucursal = Integer.parseInt(txtnumsuc.getText());
        }
        } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Ingrese un número válido para  N° SUCURSAL");
        datosValidos = false; // Marcar los datos como no válidos
        }
       
        try {
        telefono = Integer.parseInt(txttelf.getText());
        if (String.valueOf(telefono).length() != 7) {
        JOptionPane.showMessageDialog(null, "El teléfono debe tener 7 dígitos");
        datosValidos = false; // Marcar los datos como no válidos
        }
        } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Ingrese un número válido para el teléfono");
        datosValidos = false;}
       

       if (datosValidos) {
        HSucursales hs = new HSucursales(Sucursal, nombre, dni, telefono, distrito, direcc);
        hSucursalesArray.agregarsSucursal(hs);
        for (int i = 0; i < hSucursalesArray.tamañoArreglo(); i++) {
             Object[] fila={
            hSucursalesArray.obtener(i).getNumSucursal(),
            hSucursalesArray.obtener(i).getTelefono(),
            hSucursalesArray.obtener(i).getCiudad(),
            hSucursalesArray.obtener(i).getDirección(),
            hSucursalesArray.obtener(i).getEncargado(),
            hSucursalesArray.obtener(i).getDNI()
        };
            tprincipal.addRow(fila);  
           }

                //agregar datos a la BDD
                try {
                PreparedStatement pps=  cn.prepareStatement("INSERT INTO sucursalpri(NumeroSuc,Telefono,Ciudad,Direccion,Encargado,DNI) VALUES(?,?,?,?,?,?)");
                pps.setInt(1, Sucursal);
                pps.setInt(2, telefono);
                pps.setString(3, distrito);
                pps.setString(4, direcc);
                pps.setString(5, nombre);
                pps.setInt(6, dni);
                pps.executeUpdate();
                JOptionPane.showMessageDialog(null, "Sucursal Agregada");
            } catch (SQLException ex) {
                Logger.getLogger(FrameProductos.class.getName()).log(Level.SEVERE, null, ex);
                mostrartablaprin();
                JOptionPane.showMessageDialog(null, ex);
            }
           
        }

       } 
    }//GEN-LAST:event_botonIngrActionPerformed
    public static boolean validarLetras(String datos){
        return datos.matches("[a-zA-Z .]*");
    }
    private void botonLimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLimActionPerformed
        // TODO add your handling code here:
        // Limpiar los campos de texto
        txtnumsuc.setText("");
        txtNombre.setText("");
        txtdni.setText("");
        txttelf.setText("");
        txtciudad.setText("");
        txtdire.setText("");

    }//GEN-LAST:event_botonLimActionPerformed

    private void txtnumsuc2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnumsuc2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnumsuc2ActionPerformed

    private void txtnombreenc2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombreenc2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombreenc2ActionPerformed

    private void txttelef2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttelef2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttelef2ActionPerformed
    public void mostrartablaprovin(){
        tprovincia = new DefaultTableModel();
        tprovincia.addColumn("Número Sucursal");
        tprovincia.addColumn("Teléfono");
        tprovincia.addColumn("Cod. Provincia");
        tprovincia.addColumn("Provincia");
        tprovincia.addColumn("Ciudad");
        tprovincia.addColumn("Dirección");
        tprovincia.addColumn("Encargado");
        tprovincia.addColumn("DNI");
        tblprovin.setModel(tprovincia);
        
        
        String sql="Select * From sucursalpro";
        String datos []= new String [8];
        Statement st;
        
        try{
            st= cn.createStatement();
            ResultSet rs=st.executeQuery(sql);
            while(rs.next()){
                
                datos[0]=rs.getString(1);
                datos[1]=rs.getString(2);
                datos[2]=rs.getString(3);
                datos[3]=rs.getString(4);
                datos[4]=rs.getString(5);
                datos[5]=rs.getString(6);
                datos[6]=rs.getString(7);
                datos[7]=rs.getString(8);
                tprovincia.addRow(datos);
            }
            tblprovin.setModel(tprovincia);
        }catch(SQLException ex){
            Logger.getLogger(FrameProductos.class.getName()).log(Level.SEVERE,null,ex);
        }
        
        
    }
    private void botonIngProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIngProvActionPerformed
        // TODO add your handling code here:
        // Obtener los datos de los otros 8 campos de texto
        int numSucursal = 0;
        int dni = 0;
        int telefono = 0;
        int codProv = 0;
        boolean datosValidos = true;
        
        if(txtnumsuc2.getText().trim().isEmpty() || txtnombreenc2.getText().trim().isEmpty()|| txtdni2.getText().trim().isEmpty()|| txttelef2.getText().trim().isEmpty()|| txtciudad2.getText().trim().isEmpty()|| txttelef2.getText().trim().isEmpty() || txtdirec2.getText().trim().isEmpty()|| txtprovi2.getText().trim().isEmpty()||txtcodprovi2.getText().trim().isEmpty())     {
        JOptionPane.showMessageDialog(null, "Complete los campos");
        datosValidos = false;}
        else{
        String nombreenca=txtnombreenc2.getText();
        if (!validarLetras(txtnombreenc2.getText())) 
        {JOptionPane.showMessageDialog(null, "Error al ingresar dato NOMBRE DEL ENCARGADO");
        datosValidos = false;}
        
        String ciudad =txtciudad2.getText();
        if (!validarLetras(txtciudad2.getText())) 
        {JOptionPane.showMessageDialog(null, "Error al ingresar dato CIUDAD");
        datosValidos = false;}
        
        String direcc =txtdirec2.getText();
        if (!validarLetras(txtdirec2.getText())) 
        {JOptionPane.showMessageDialog(null, "Error al ingresar dato DIRECCION");
        datosValidos = false;}
        
        String nomprov =txtprovi2.getText();
        if (!validarLetras(txtprovi2.getText())) 
        {JOptionPane.showMessageDialog(null, "Error al ingresar dato PROVINCIA");
        datosValidos = false;}
        
        try {
        dni= Integer.parseInt(txtdni2.getText());
        if (txtdni2.getText().length() != 8) {
        JOptionPane.showMessageDialog(null, "El DNI debe tener 8 dígitos");
        datosValidos = false; // Marcar los datos como no válidos
        } else {
        dni = Integer.parseInt(txtdni2.getText());
        }
        } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Ingrese un número válido para DNI");
        datosValidos = false; // Marcar los datos como no válidos
        }

       
        try {
        numSucursal=Integer.parseInt(txtnumsuc2.getText());
        if (txtnumsuc2.getText().length() != 5) {
        JOptionPane.showMessageDialog(null, "El N° DE SUCURSAL debe tener 5 dígitos");
        datosValidos = false; // Marcar los datos como no válidos
        } else {
        numSucursal = Integer.parseInt(txtnumsuc2.getText());
        }
        } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Ingrese un número válido para N° DE SUCURSAL");
        datosValidos = false; // Marcar los datos como no válidos
        }
       
        try {
        telefono = Integer.parseInt(txttelef2.getText());
        if (String.valueOf(telefono).length() != 7) {
        JOptionPane.showMessageDialog(null, "El teléfono debe tener 7 dígitos");
        datosValidos = false; // Marcar los datos como no válidos
        }
        } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Ingrese un número válido para el teléfono");
        datosValidos = false;}
        
        try{
        codProv = Integer.parseInt(txtcodprovi2.getText());
        if (String.valueOf(codProv).length() != 5) {
        JOptionPane.showMessageDialog(null, "El CP debe tener 5 dígitos");
        datosValidos = false; // Marcar los datos como no válidos
        }
        } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Ingrese un número válido para el año");
        datosValidos = false;}
                 
        if (datosValidos) {
         HSucursalesProvincia provincia = new HSucursalesProvincia(nomprov, codProv, numSucursal, nombreenca, dni, telefono, ciudad, direcc);
            hspa.agregarSucursalH(provincia);
            for (int i = 0; i < hspa.tamañoArreglo(); i++) {
                Object[] fila={
                    hspa.obtener(i).getNumSucursal(),
                    hspa.obtener(i).getTelefono(),
                    hspa.obtener(i).getCodigoProvincia(),
                    hspa.obtener(i).getProvincia(),
                    hspa.obtener(i).getCiudad(),
                    hspa.obtener(i).getDirección(),
                    hspa.obtener(i).getEncargado(),
                    hspa.obtener(i).getDNI()
 
        };
            tprovincia.addRow(fila);
            }
            
            //Agregar a BDD
            try {
                PreparedStatement pps=  cn.prepareStatement("INSERT INTO sucursalpro(NumeroSuc,Telefono,CodPro,Provincia,Ciudad,Direccion,Encargado,DNI) VALUES(?,?,?,?,?,?,?,?)");
                pps.setInt(1, numSucursal);
                pps.setInt(2, telefono);
                pps.setInt(3, codProv);
                pps.setString(4, nomprov);
                pps.setString(5, ciudad);
                pps.setString(6, direcc);
                pps.setString(7, nombreenca);
                pps.setInt(8, dni);
                pps.executeUpdate();
                JOptionPane.showMessageDialog(null, "Sucursal Prov. Agregada");
            } catch (SQLException ex) {
                Logger.getLogger(FrameProductos.class.getName()).log(Level.SEVERE, null, ex);
                mostrartablaprovin();
                JOptionPane.showMessageDialog(null, ex);
            }
        }
       
        }

    }//GEN-LAST:event_botonIngProvActionPerformed

    private void botonLimProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLimProvActionPerformed

        // Limpiar los campos de texto
        txtnumsuc2.setText("");
        txtnombreenc2.setText("");
        txtdni2.setText("");
        txttelef2.setText("");
        txtciudad2.setText("");
        txtdirec2.setText("");
        txtprovi2.setText("");
        txtcodprovi2.setText("");

    }//GEN-LAST:event_botonLimProvActionPerformed

    private void txtnumsucKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnumsucKeyTyped

        if(txtnumsuc.getText().length() >=5)
        {
            evt.consume();
        }     
    }//GEN-LAST:event_txtnumsucKeyTyped

    private void txtciudadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtciudadKeyTyped
    // TODO add your handling code here:
    }//GEN-LAST:event_txtciudadKeyTyped

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped

    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtdniKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdniKeyTyped

        if(txtdni.getText().length() >=8)
        {
            evt.consume();
        }  // TODO add your handling code here:
    }//GEN-LAST:event_txtdniKeyTyped

    private void txttelfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttelfKeyTyped
  
        if(txttelf.getText().length() >=7)
        {
            evt.consume();
        } 
    }//GEN-LAST:event_txttelfKeyTyped

    private void txtnumsuc2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnumsuc2KeyTyped

        if(txtnumsuc2.getText().length() >=5)
        {
            evt.consume();
        }        // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnumsuc2KeyTyped

    private void txttelef2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttelef2KeyTyped

        if(txttelef2.getText().length() >=7)
        {
            evt.consume();
        }              // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_txttelef2KeyTyped

    private void txtdni2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdni2KeyTyped

        if(txtdni2.getText().length() >=8)
        {
            evt.consume();
        } 
                // TODO add your handling code here:
    }//GEN-LAST:event_txtdni2KeyTyped

    private void txtprovi2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtprovi2KeyTyped

    }//GEN-LAST:event_txtprovi2KeyTyped

    private void txtciudad2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtciudad2KeyTyped
  // TODO add your handling code here:
    }//GEN-LAST:event_txtciudad2KeyTyped

    private void txtnombreenc2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombreenc2KeyTyped
     // TODO add your handling code here:
    }//GEN-LAST:event_txtnombreenc2KeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
FramePrincipal abrir = new FramePrincipal();
   abrir.setVisible(true);
   this.setVisible(false);             // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
FramePrincipal abrir = new FramePrincipal();
   abrir.setVisible(true);
   this.setVisible(false);          // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtcodprovi2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcodprovi2KeyTyped
                 if(txtcodprovi2.getText().length() >=5)
        {
            evt.consume();
        }     // TODO add your handling code here:
   // TODO add your handling code here:
    }//GEN-LAST:event_txtcodprovi2KeyTyped

    private void txtprovi2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprovi2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprovi2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameSucursales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameSucursales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameSucursales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameSucursales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new FrameSucursales().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane JtabbedPane;
    private javax.swing.JButton botonIngProv;
    private javax.swing.JButton botonIngr;
    private javax.swing.JButton botonLim;
    private javax.swing.JButton botonLimProv;
    private javax.swing.JLabel ciudadProv;
    private javax.swing.JLabel codProv;
    private javax.swing.JLabel direccionProv;
    private javax.swing.JLabel dniProv;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel jlabelciudad;
    private javax.swing.JLabel jlabeldireccion;
    private javax.swing.JLabel jlabeldni;
    private javax.swing.JLabel jlabelnomEncargado;
    private javax.swing.JLabel jlabelnumsucursal;
    private javax.swing.JLabel jlabeltelf;
    private javax.swing.JLabel numEncargProv;
    private javax.swing.JLabel numSucursalProv;
    private javax.swing.JLabel provincia;
    private javax.swing.JTable tblprincipal;
    private javax.swing.JTable tblprovin;
    private javax.swing.JLabel telefonoProv;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtciudad;
    private javax.swing.JTextField txtciudad2;
    private javax.swing.JTextField txtcodprovi2;
    private javax.swing.JTextField txtdire;
    private javax.swing.JTextField txtdirec2;
    private javax.swing.JTextField txtdni;
    private javax.swing.JTextField txtdni2;
    private javax.swing.JTextField txtnombreenc2;
    private javax.swing.JTextField txtnumsuc;
    private javax.swing.JTextField txtnumsuc2;
    private javax.swing.JTextField txtprovi2;
    private javax.swing.JTextField txttelef2;
    private javax.swing.JTextField txttelf;
    // End of variables declaration//GEN-END:variables

}
