package Framesregis;

import ArrayList.PComidaArray;
import ArrayList.PHigieneArray;
import ArrayList.PMakeupArray;
import CGen.Generico1;
import Clases.PComida;
import Clases.PHigiene;
import Clases.PMakeup;
import conexionbd.Conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;



/**
 *
 * @author Omar Tc
 */
public class FrameProductos extends javax.swing.JFrame {
    
    Conexion db= new Conexion();
    Connection cn=  db.conectar();
    
    DefaultTableModel tHigiene = new DefaultTableModel();
    DefaultTableModel tComida = new DefaultTableModel();
    DefaultTableModel tMakeup = new DefaultTableModel();

    PHigieneArray higieneArray = new PHigieneArray();
    PComidaArray comidaArray = new PComidaArray();
    PMakeupArray makeupArray = new PMakeupArray();
    
    public FrameProductos() {
        initComponents();
        mostrartablaprohigi();
        mostrartablaprocomes();
        mostrartablapromake();
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        setLocationRelativeTo(null);
        db.conectar();
    }
    
    

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNamePro = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCod = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCodPro = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtStock = new javax.swing.JTextField();
        cmbtipfabri = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblHigiene = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtcontenido = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txttipo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextField2 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        txtNamePro2 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtCod2 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtCodPro2 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtPrecio2 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtStock2 = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblComida = new javax.swing.JTable();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtcaducidad1 = new javax.swing.JTextField();
        cmbTipocomes = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        txtNamePro3 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txtCod3 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txtCodPro3 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        txtPrecio3 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        txtStock3 = new javax.swing.JTextField();
        cmbtipfabri3 = new javax.swing.JComboBox<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblMakeup = new javax.swing.JTable();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        txttonos3 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        txttipo3 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtdiri3 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(153, 217, 234));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nombre del Producto:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, 200, -1));

        txtNamePro.setBackground(new java.awt.Color(246, 241, 241));
        txtNamePro.setForeground(new java.awt.Color(0, 0, 0));
        txtNamePro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNameProKeyTyped(evt);
            }
        });
        jPanel2.add(txtNamePro, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, 150, -1));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Código:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 120, 20));

        txtCod.setBackground(new java.awt.Color(246, 241, 241));
        txtCod.setForeground(new java.awt.Color(0, 0, 0));
        txtCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodActionPerformed(evt);
            }
        });
        txtCod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodKeyTyped(evt);
            }
        });
        jPanel2.add(txtCod, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 120, -1));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Codigo Proveedor:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 150, -1));

        txtCodPro.setBackground(new java.awt.Color(246, 241, 241));
        txtCodPro.setForeground(new java.awt.Color(0, 0, 0));
        txtCodPro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodProKeyTyped(evt);
            }
        });
        jPanel2.add(txtCodPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 130, -1));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Tipo Fabricado:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 70, 160, -1));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Precio:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, 100, -1));

        txtPrecio.setBackground(new java.awt.Color(246, 241, 241));
        txtPrecio.setForeground(new java.awt.Color(0, 0, 0));
        txtPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecioKeyTyped(evt);
            }
        });
        jPanel2.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 160, 100, -1));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Stock:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 140, 90, -1));

        txtStock.setBackground(new java.awt.Color(246, 241, 241));
        txtStock.setForeground(new java.awt.Color(0, 0, 0));
        txtStock.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtStockKeyTyped(evt);
            }
        });
        jPanel2.add(txtStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 160, 90, -1));

        cmbtipfabri.setBackground(new java.awt.Color(246, 241, 241));
        cmbtipfabri.setForeground(new java.awt.Color(0, 0, 0));
        cmbtipfabri.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Seleccionar--", "90% Natural", "50% Natural" }));
        cmbtipfabri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbtipfabriActionPerformed(evt);
            }
        });
        jPanel2.add(cmbtipfabri, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 100, 120, -1));

        tblHigiene.setBackground(new java.awt.Color(246, 241, 241));
        tblHigiene.setForeground(new java.awt.Color(0, 0, 0));
        tblHigiene.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Cod.Proveedor", "Nombre", "Tipo Fab.", "Contenido", "Tipo", "Precio", "Stock"
            }
        ));
        tblHigiene.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHigieneMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblHigiene);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 780, 260));

        jButton1.setBackground(new java.awt.Color(0, 162, 232));
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Insertar");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, 100, 30));

        jButton2.setBackground(new java.awt.Color(237, 28, 36));
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Eliminar");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 470, -1, 30));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setText("Limpiar");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 470, -1, 30));

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Contenido:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 100, -1));

        txtcontenido.setBackground(new java.awt.Color(246, 241, 241));
        txtcontenido.setForeground(new java.awt.Color(0, 0, 0));
        txtcontenido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcontenidoActionPerformed(evt);
            }
        });
        txtcontenido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcontenidoKeyTyped(evt);
            }
        });
        jPanel2.add(txtcontenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 100, -1));

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Tipo");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 90, -1));

        txttipo.setBackground(new java.awt.Color(246, 241, 241));
        txttipo.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(txttipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, 90, -1));
        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(7, 62, 91));
        jTextField2.setFont(new java.awt.Font("Stencil", 2, 36)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(246, 241, 241));
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("REGISTROS DE PRODUCTOS DE HIGIENE");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 60));

        jButton4.setBackground(new java.awt.Color(255, 0, 0));
        jButton4.setForeground(new java.awt.Color(0, 0, 0));
        jButton4.setText("VOLVER");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 470, 80, 30));

        jTabbedPane1.addTab("Higiene", jPanel2);

        jPanel5.setBackground(new java.awt.Color(153, 217, 234));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setBackground(new java.awt.Color(0, 0, 0));
        jLabel17.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Nombre del Producto:");
        jPanel5.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, 190, -1));

        txtNamePro2.setBackground(new java.awt.Color(246, 241, 241));
        txtNamePro2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel5.add(txtNamePro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, 130, -1));

        jLabel18.setBackground(new java.awt.Color(0, 0, 0));
        jLabel18.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Codigo:");
        jPanel5.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 120, -1));

        txtCod2.setBackground(new java.awt.Color(246, 241, 241));
        txtCod2.setForeground(new java.awt.Color(0, 0, 0));
        txtCod2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCod2KeyTyped(evt);
            }
        });
        jPanel5.add(txtCod2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 120, -1));

        jLabel19.setBackground(new java.awt.Color(0, 0, 0));
        jLabel19.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Codigo Proveedor:");
        jPanel5.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 130, -1));

        txtCodPro2.setBackground(new java.awt.Color(246, 241, 241));
        txtCodPro2.setForeground(new java.awt.Color(0, 0, 0));
        txtCodPro2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodPro2KeyTyped(evt);
            }
        });
        jPanel5.add(txtCodPro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 130, -1));

        jLabel21.setBackground(new java.awt.Color(0, 0, 0));
        jLabel21.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Precio:");
        jPanel5.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 90, -1));

        txtPrecio2.setBackground(new java.awt.Color(246, 241, 241));
        txtPrecio2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel5.add(txtPrecio2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 90, -1));

        jLabel22.setBackground(new java.awt.Color(0, 0, 0));
        jLabel22.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Stock:");
        jPanel5.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, 90, -1));

        txtStock2.setBackground(new java.awt.Color(246, 241, 241));
        txtStock2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel5.add(txtStock2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 90, -1));

        tblComida.setBackground(new java.awt.Color(246, 241, 241));
        tblComida.setForeground(new java.awt.Color(0, 0, 0));
        tblComida.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Cod.Proveedor", "Nombre", "Tipo", "Precio", "Stock", "Caducidad"
            }
        ));
        tblComida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblComidaMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblComida);

        jPanel5.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 760, 260));

        jButton7.setBackground(new java.awt.Color(0, 162, 232));
        jButton7.setForeground(new java.awt.Color(0, 0, 0));
        jButton7.setText("Insertar");
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, 100, 30));

        jButton8.setBackground(new java.awt.Color(237, 28, 36));
        jButton8.setForeground(new java.awt.Color(0, 0, 0));
        jButton8.setText("Eliminar");
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 470, 110, 30));

        jButton9.setBackground(new java.awt.Color(255, 255, 255));
        jButton9.setForeground(new java.awt.Color(0, 0, 0));
        jButton9.setText("Limpiar");
        jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 470, -1, 30));

        jLabel24.setBackground(new java.awt.Color(0, 0, 0));
        jLabel24.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 0));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Tipo:");
        jPanel5.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 70, 120, -1));

        jLabel20.setBackground(new java.awt.Color(0, 0, 0));
        jLabel20.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Caducidad:");
        jPanel5.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, 100, -1));

        txtcaducidad1.setBackground(new java.awt.Color(246, 241, 241));
        txtcaducidad1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel5.add(txtcaducidad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, 100, -1));

        cmbTipocomes.setBackground(new java.awt.Color(246, 241, 241));
        cmbTipocomes.setForeground(new java.awt.Color(0, 0, 0));
        cmbTipocomes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Selecionar--", "Fruta/Verdura", "Embutidos", "Otros", "Bebida", "Proteina" }));
        jPanel5.add(cmbTipocomes, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 100, 120, -1));

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(7, 62, 91));
        jTextField1.setFont(new java.awt.Font("Stencil", 2, 36)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(246, 241, 241));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("REGISTROS DE PRODUCTOS COMESTIBLES");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel5.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 60));

        jButton5.setBackground(new java.awt.Color(255, 0, 0));
        jButton5.setForeground(new java.awt.Color(0, 0, 0));
        jButton5.setText("VOLVER");
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 470, 90, 30));

        jTabbedPane1.addTab("Comestible", jPanel5);

        jPanel7.setBackground(new java.awt.Color(153, 217, 234));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 0));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Nombre del Producto:");
        jPanel7.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, 190, -1));

        txtNamePro3.setBackground(new java.awt.Color(246, 241, 241));
        txtNamePro3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel7.add(txtNamePro3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, 130, -1));

        jLabel26.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 0, 0));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("Codigo:");
        jPanel7.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 90, -1));

        txtCod3.setBackground(new java.awt.Color(246, 241, 241));
        txtCod3.setForeground(new java.awt.Color(0, 0, 0));
        txtCod3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCod3KeyTyped(evt);
            }
        });
        jPanel7.add(txtCod3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 110, -1));

        jLabel27.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 0, 0));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("Codigo Proveedor:");
        jPanel7.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 180, -1));

        txtCodPro3.setBackground(new java.awt.Color(246, 241, 241));
        txtCodPro3.setForeground(new java.awt.Color(0, 0, 0));
        txtCodPro3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodPro3KeyTyped(evt);
            }
        });
        jPanel7.add(txtCodPro3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 120, -1));

        jLabel28.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 0, 0));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("Tipo Fabricado");
        jPanel7.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 80, 120, -1));

        jLabel29.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 0, 0));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("Precio:");
        jPanel7.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 90, -1));

        txtPrecio3.setBackground(new java.awt.Color(246, 241, 241));
        txtPrecio3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel7.add(txtPrecio3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 71, -1));

        jLabel30.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 0, 0));
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("Stock:");
        jPanel7.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, 90, -1));

        txtStock3.setBackground(new java.awt.Color(246, 241, 241));
        txtStock3.setForeground(new java.awt.Color(0, 0, 0));
        txtStock3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtStock3KeyTyped(evt);
            }
        });
        jPanel7.add(txtStock3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, 71, -1));

        cmbtipfabri3.setBackground(new java.awt.Color(246, 241, 241));
        cmbtipfabri3.setForeground(new java.awt.Color(0, 0, 0));
        cmbtipfabri3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Seleccionar--", "Cruelty free", "NO CF" }));
        jPanel7.add(cmbtipfabri3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 110, 120, -1));

        tblMakeup.setBackground(new java.awt.Color(246, 241, 241));
        tblMakeup.setForeground(new java.awt.Color(0, 0, 0));
        tblMakeup.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Cod.Proveedor", "Nombre", "Tipo Fab.", "Tipo", "Precio", "Stock", "Tonos", "Para"
            }
        ));
        tblMakeup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMakeupMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tblMakeup);

        jPanel7.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 760, 240));

        jButton10.setBackground(new java.awt.Color(0, 162, 232));
        jButton10.setForeground(new java.awt.Color(0, 0, 0));
        jButton10.setText("Insertar");
        jButton10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, 100, 30));

        jButton11.setBackground(new java.awt.Color(237, 28, 36));
        jButton11.setForeground(new java.awt.Color(0, 0, 0));
        jButton11.setText("Eliminar");
        jButton11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 470, 110, 30));

        jButton12.setBackground(new java.awt.Color(255, 255, 255));
        jButton12.setForeground(new java.awt.Color(0, 0, 0));
        jButton12.setText("Limpiar");
        jButton12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 470, -1, 30));

        jLabel31.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(0, 0, 0));
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("Tonos");
        jPanel7.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 150, 80, -1));

        txttonos3.setBackground(new java.awt.Color(246, 241, 241));
        txttonos3.setForeground(new java.awt.Color(0, 0, 0));
        txttonos3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttonos3ActionPerformed(evt);
            }
        });
        jPanel7.add(txttonos3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, 90, 20));

        jLabel32.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(0, 0, 0));
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText("Tipo");
        jPanel7.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 80, -1));

        txttipo3.setBackground(new java.awt.Color(246, 241, 241));
        txttipo3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel7.add(txttipo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 80, -1));

        jLabel9.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Dirigido para:");
        jPanel7.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 150, -1, -1));

        txtdiri3.setBackground(new java.awt.Color(246, 241, 241));
        txtdiri3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel7.add(txtdiri3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 180, 80, -1));

        jTextField3.setEditable(false);
        jTextField3.setBackground(new java.awt.Color(7, 62, 91));
        jTextField3.setFont(new java.awt.Font("Stencil", 2, 36)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(246, 241, 241));
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setText("REGISTROS DE PRODUCTOS DE MAQUILLAJES");
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel7.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 60));

        jButton6.setBackground(new java.awt.Color(237, 28, 36));
        jButton6.setForeground(new java.awt.Color(0, 0, 0));
        jButton6.setText("VOLVER");
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 470, 80, 30));

        jTabbedPane1.addTab("Make Up", jPanel7);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void mostrartablaprohigi(){
        
        tHigiene = new DefaultTableModel();
        tHigiene.addColumn("Código");
        tHigiene.addColumn("Nombre");
        tHigiene.addColumn("Tipo fabricado");
        tHigiene.addColumn("Tipo");
        tHigiene.addColumn("Contenido");
        tHigiene.addColumn("Precio");
        tHigiene.addColumn("Stock");
        tHigiene.addColumn("Cod. Proveedor");
        tHigiene.addColumn("COSTO TOTAL");
        tblHigiene.setModel(tHigiene);
        
        String sql="Select * From prohigi";
        String datos [] = new String [9];
        Statement st;
        
        
        
        try{
            st= cn.createStatement();
            ResultSet rs=st.executeQuery(sql);
            while(rs.next()){
                
                //usando la clase generica
                double precio=rs.getDouble("Precio");
                int Stock = rs.getInt("Stock");
                Generico1<Double,Integer> generico = new Generico1<>(precio,Stock);
                double total=generico.multiplicar();
                
                datos[0]=rs.getString(1);
                datos[1]=rs.getString(2);
                datos[2]=rs.getString(3);
                datos[3]=rs.getString(4);
                datos[4]=rs.getString(5);
                datos[5]=rs.getString(6);
                datos[6]=rs.getString(7);
                datos[7]=rs.getString(8);
                datos[8]=String.valueOf(total);
                tHigiene.addRow(datos);
            }
            tblHigiene.setModel(tHigiene);
        }catch(SQLException ex){
            Logger.getLogger(FrameProductos.class.getName()).log(Level.SEVERE,null,ex);
        }
    }
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //Comprobar todos los campos
        int codigo = 0;
        int codproveedor = 0;
        double precio = 0;
        int stock = 0;
        double contenido = 0;
        boolean datosValidos = true;
        
        if(cmbtipfabri.getSelectedIndex()==0||txtCod.getText().trim().isEmpty()|| txtCodPro.getText().trim().isEmpty()||txtNamePro.getText().trim().isEmpty()||
            txttipo.getText().trim().isEmpty()||txtPrecio.getText().trim().isEmpty()||txtStock.getText().trim().isEmpty()
            ||txtcontenido.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Complete todos los campos");
            datosValidos = false;} 
        
        else{
        String tipoFab=cmbtipfabri.getSelectedItem().toString();
        String nombre_producto=txtNamePro.getText();
        
        if (!validarLetras(txtNamePro.getText())) 
        {JOptionPane.showMessageDialog(null, "Error al ingresar dato NOMBRE DEL PRODUCTO");
        datosValidos = false;}
        
        String tipo=txttipo.getText();
        if (!validarLetras(txttipo.getText())) 
        {JOptionPane.showMessageDialog(null, "Error al ingresar dato tipo");
        datosValidos = false;}
        
        
        try {
        codigo = Integer.parseInt(txtCod.getText());
        if (String.valueOf(codigo).length() != 6) {
        JOptionPane.showMessageDialog(null, "El código debe tener 6 dígitos");
        datosValidos = false; // Marcar los datos como no válidos
        }
        } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Ingrese un número válido para el código");
        datosValidos = false; // Marcar los datos como no válidos
        }


        try {
        codproveedor = Integer.parseInt(txtCodPro.getText());
        if (String.valueOf(codproveedor).length() != 6) {
        JOptionPane.showMessageDialog(null, "El código de proveedor debe tener 6 dígitos");
        datosValidos = false; 
        }
        } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Ingrese un número válido para el código de proveedor");
        datosValidos = false; 
        }
        
        try{
        precio=Double.parseDouble(txtPrecio.getText());
        stock= Integer.parseInt(txtStock.getText());
        contenido=Double.parseDouble(txtcontenido.getText());
        } 
        catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "ERROR EN UNO DE LOS CAMPOS: PRECIO, STOCK O CONTENIDO");
        datosValidos = false;
        
        
    } 
            
        
        
        //USAMOS LA CLASE GENERICA
        Generico1<Double, Integer> generico1= new Generico1(precio, stock);
        double resultado = generico1.multiplicar();
        
     if (datosValidos) {
         PHigiene ph = new PHigiene(nombre_producto, codigo, codproveedor, tipo, precio, stock, contenido, tipoFab);
         higieneArray.agregarProductoH(ph);
         
         for (int o = 0; o < higieneArray.tamañoArreglo(); o++) {
             Object[] fila={
                 higieneArray.obtener(o).getCodigo(),
                 higieneArray.obtener(o).getNombre_producto(),
                 higieneArray.obtener(o).getTipoFabricado(),
                 higieneArray.obtener(o).getTipo(),
                 higieneArray.obtener(o).getContenido(),
                 higieneArray.obtener(o).getPrecio(),
                 higieneArray.obtener(o).getStock(),
                 higieneArray.obtener(o).getCodproveedor(),
                 resultado
             };
             tHigiene.addRow(fila);
         }
         //agregar datos a la BDD
            try {
                PreparedStatement pps=  cn.prepareStatement("INSERT INTO prohigi(Codigo,Nombreprod,TipFabri,Tipo,Contenido,Precio,Stock,CodProv) VALUES(?,?,?,?,?,?,?,?)");
                pps.setInt(1, codigo);
                pps.setString(2, nombre_producto);
                pps.setString(3, tipoFab);
                pps.setString(4, tipo);
                pps.setDouble(5, contenido);
                pps.setDouble(6, precio);
                pps.setInt(7, stock);
                pps.setInt(8, codproveedor);
                pps.executeUpdate();
                JOptionPane.showMessageDialog(null, "Producto Guardado");
            } catch (SQLException ex) {
                Logger.getLogger(FrameProductos.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
       
        
        } 
    }//GEN-LAST:event_jButton1ActionPerformed
    public static boolean validarLetras(String datos){
        return datos.matches("[a-zA-Z ]*");
    }

    public void mostrar(String tabla){
        
        
    }

    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       DefaultTableModel model = (DefaultTableModel) tblHigiene.getModel();
        if(tblHigiene.getSelectedRowCount()== 1){
            model.removeRow(tblHigiene.getSelectedRow());
            
        }else{
            if(tblHigiene.getRowCount()== 0){
                JOptionPane.showMessageDialog(null,"La tabla esta vacía");
                           
            }else{ 
                JOptionPane.showMessageDialog(null, "Debe seleccionar una fila");
            }
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        //Elimina Campos del formulario
        txtCod.setText("");
        txtCodPro.setText("");
        txtNamePro.setText("");
        txtPrecio.setText("");
        txtStock.setText("");
        txtcontenido.setText("");
        txttipo.setText("");
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tblHigieneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHigieneMouseClicked

        
    }//GEN-LAST:event_tblHigieneMouseClicked

    private void tblComidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblComidaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblComidaMouseClicked
    
    private void mostrartablaprocomes(){
        
        tComida = new DefaultTableModel();
        tComida.addColumn("Código");
        tComida.addColumn("Nombre");
        tComida.addColumn("Tipo");
        tComida.addColumn("Precio");
        tComida.addColumn("Stock");
        tComida.addColumn("Caducidad");
        tComida.addColumn("Cod. Proveedor");
        tComida.addColumn("COSTO TOTAL");
        tblComida.setModel(tComida);
        
        String sql="Select * From procomes";
        String datos [] = new String [8];
        Statement st;
        
        
        
        try{
            st= cn.createStatement();
            ResultSet rs=st.executeQuery(sql);
            while(rs.next()){
                
                //usando la clase generica
                double precio=rs.getDouble("Precio");
                int Stock = rs.getInt("Stock");
                Generico1<Double,Integer> generico = new Generico1<>(precio,Stock);
                double total=generico.multiplicar();
                
                datos[0]=rs.getString(1);
                datos[1]=rs.getString(2);
                datos[2]=rs.getString(3);
                datos[3]=rs.getString(4);
                datos[4]=rs.getString(5);
                datos[5]=rs.getString(6);
                datos[6]=rs.getString(7);
                datos[7]=String.valueOf(total);
                tComida.addRow(datos);
            }
            tblComida.setModel(tComida);
        }catch(SQLException ex){
            Logger.getLogger(FrameProductos.class.getName()).log(Level.SEVERE,null,ex);
        }
    }
    
    
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        int cod = 0;
        int codprove2 = 0;
        double prec2 = 0;
        int stock2 = 0;
        int caduci = 0;
        boolean datosValidos = true;
        
        if(cmbTipocomes.getSelectedIndex()==0||txtCod2.getText().trim().isEmpty()||txtCodPro2.getText().trim().isEmpty()||txtNamePro2.getText().trim().isEmpty()
        ||txtPrecio2.getText().trim().isEmpty()||txtStock2.getText().trim().isEmpty()){
        JOptionPane.showMessageDialog(null, "Complete todos los campos");
        datosValidos = false;}
        else{
            
        String namepro2=txtNamePro2.getText();
        if (!validarLetras(txtNamePro2.getText())) 
        {JOptionPane.showMessageDialog(null, "Error al ingresar dato NOMBRE COMPLETO");
        datosValidos = false;}
        
        String tipo2=cmbTipocomes.getSelectedItem().toString();
        
        try {
        cod = Integer.parseInt(txtCod2.getText());
        if (String.valueOf(cod).length() != 6) {
        JOptionPane.showMessageDialog(null, "El código debe tener 6 dígitos");
        datosValidos = false; // Marcar los datos como no válidos
        }
        } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Ingrese un número válido para el código");
        datosValidos = false; // Marcar los datos como no válidos
        }


        try {
        codprove2 = Integer.parseInt(txtCodPro2.getText());
        if (String.valueOf(codprove2).length() != 6) {
        JOptionPane.showMessageDialog(null, "El código de proveedor debe tener 6 dígitos");
        datosValidos = false; // Marcar los datos como no válidos
        }
        } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Ingrese un número válido para el código de proveedor");
        datosValidos = false; // Marcar los datos como no válidos
        }
        
        try{         
         prec2= Double.parseDouble(txtPrecio2.getText());
         stock2=Integer.parseInt(txtStock2.getText());
         caduci=Integer.parseInt(txtcaducidad1.getText());
        } 
        catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "ERROR EN UNO DE LOS CAMPOS: PRECIO, STOCK O CADUCIDAD");
        datosValidos = false;
        }
        
        
        
        
        //Usando clases genericas
        Generico1<Double, Integer> generico1= new Generico1(prec2, stock2);
        double resultado = generico1.multiplicar();
        if (datosValidos) {
            PComida pc = new PComida(namepro2, cod, codprove2, tipo2, prec2, stock2, caduci);
            comidaArray.agregarProductoC(pc);
            
            for (int i = 0; i < comidaArray.tamañoArreglo(); i++) {
                Object[] fila={
                  comidaArray.obtener(i).getCodigo(),
                  comidaArray.obtener(i).getNombre_producto(),
                  comidaArray.obtener(i).getTipo(),
                  comidaArray.obtener(i).getPrecio(),
                  comidaArray.obtener(i).getStock(),
                  comidaArray.obtener(i).getCaducidad(),
                  comidaArray.obtener(i).getCodproveedor(),
                  resultado
                };
                tComida.addRow(fila);
            }
        //agregar datos a la BDD
            try {
                PreparedStatement pps=  cn.prepareStatement("INSERT INTO procomes(Codigo,Nombreprod,Tipo,Precio,Stock,Caducidad,CodProv) VALUES(?,?,?,?,?,?,?)");
                pps.setInt(1, cod);
                pps.setString(2, namepro2);
                pps.setString(3, tipo2);
                pps.setDouble(4, prec2);
                pps.setInt(5, stock2);
                pps.setInt(6, caduci);
                pps.setInt(7, codprove2);
                pps.executeUpdate();
                JOptionPane.showMessageDialog(null, "Producto Guardado");
            } catch (SQLException ex) {
                Logger.getLogger(FrameProductos.class.getName()).log(Level.SEVERE, null, ex);
            }
        }  
        
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        
      DefaultTableModel model = (DefaultTableModel) tblComida.getModel();
        if(tblComida.getSelectedRowCount()== 1){
            model.removeRow(tblComida.getSelectedRow());
            
        }else{
            if(tblComida.getRowCount()== 0){
                JOptionPane.showMessageDialog(null,"La tabla esta vacía");
                           
            }else{ 
                JOptionPane.showMessageDialog(null, "Debe seleccionar una fila");
            }
        }
        
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        
        txtCod2.setText("");
        txtCodPro2.setText("");
        txtNamePro2.setText("");
        txtPrecio2.setText("");
        txtStock2.setText("");
        txtcaducidad1.setText("");
        
    }//GEN-LAST:event_jButton9ActionPerformed

    private void tblMakeupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMakeupMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblMakeupMouseClicked

    private void mostrartablapromake(){
        
        tMakeup = new DefaultTableModel();
        tMakeup.addColumn("Código");
        tMakeup.addColumn("Nombre");
        tMakeup.addColumn("Precio");
        tMakeup.addColumn("Stock");
        tMakeup.addColumn("Fabricados");
        tMakeup.addColumn("Tipos");
        tMakeup.addColumn("Tonos");
        tMakeup.addColumn("Dirigido para:");
        tMakeup.addColumn("Cod. Proveedor");
        tMakeup.addColumn("COSTO TOTAL");
        tblMakeup.setModel(tMakeup);
        
        String sql="Select * From promakeup";
        String datos [] = new String [10];
        Statement st;
        
        
        
        try{
            st= cn.createStatement();
            ResultSet rs=st.executeQuery(sql);
            while(rs.next()){
                
                //usando la clase generica
                double precio=rs.getDouble("Precio");
                int Stock = rs.getInt("Stock");
                Generico1<Double,Integer> generico = new Generico1<>(precio,Stock);
                double total=generico.multiplicar();
                
                datos[0]=rs.getString(1);
                datos[1]=rs.getString(2);
                datos[2]=rs.getString(3);
                datos[3]=rs.getString(4);
                datos[4]=rs.getString(5);
                datos[5]=rs.getString(6);
                datos[6]=rs.getString(7);
                datos[7]=rs.getString(8);
                datos[8]=rs.getString(9);
                datos[9]=String.valueOf(total);
                tMakeup.addRow(datos);
            }
            tblMakeup.setModel(tMakeup);
        }catch(SQLException ex){
            Logger.getLogger(FrameProductos.class.getName()).log(Level.SEVERE,null,ex);
        }
    }
    
    
    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        int cod = 0;
        int codpro = 0;
        int stock = 0;
        double prec = 0;
        boolean datosValidos = true;
        
        
        if(cmbtipfabri3.getSelectedIndex()==0||txtCod3.getText().trim().isEmpty()||txtCodPro3.getText().trim().isEmpty()||txtPrecio3.getText().trim().isEmpty()
                ||txtStock3.getText().trim().isEmpty()||txttonos3.getText().trim().isEmpty()||txtdiri3.getText().trim().isEmpty()){
        JOptionPane.showMessageDialog(null, "Complete todos los campos");
        datosValidos = false;} 
        else{
        String namepro=txtNamePro3.getText();
        if (!validarLetras(txtNamePro2.getText())) 
        {JOptionPane.showMessageDialog(null, "Error al ingresar el dato NOMBRE PRODUCTO");
        datosValidos = false;}
        
        String tonos= txttonos3.getText();
        if (!validarLetras(txtNamePro2.getText())) 
        {JOptionPane.showMessageDialog(null, "Error al ingresar el dato TONOS");
        datosValidos = false;}
        
        String diri=txtdiri3.getText();
        String fabri=cmbtipfabri3.getSelectedItem().toString();
       
        
        String tipo= txttipo3.getText();
        if (!validarLetras(txtNamePro2.getText())) 
        {JOptionPane.showMessageDialog(null, "Error al ingresar el dato TIPO");
        datosValidos = false;}
        
        try {
            
        cod = Integer.parseInt(txtCod3.getText());
        if (txtCod3.getText().length() != 6) {
        JOptionPane.showMessageDialog(null, "El CÓDIGO debe tener 6 dígitos");
        datosValidos = false; // Marcar los datos como no válidos
        } else {
        cod = Integer.parseInt(txtCod3.getText());
        }
       
        } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Ingrese un número válido para el código");
        datosValidos = false; // Marcar los datos como no válidos
        }


        try {
        codpro = Integer.parseInt(txtCodPro3.getText());
        if (txtCodPro3.getText().length() != 6) {
        JOptionPane.showMessageDialog(null, "El CÓDIGO PROVEEDOR debe tener 6 dígitos");
        datosValidos = false;    }}
        catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Ingrese un número válido para el código de proveedor");
        datosValidos = false; // Marcar los datos como no válidos
        }
        
        try{
         stock=Integer.parseInt(txtStock3.getText());
         prec=Double.parseDouble(txtPrecio3.getText());
        } 
         catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "ERROR EN UNO DE LOS CAMPOS: PRECIO O STOCK ");
        datosValidos = false;
    } 
        
        
        
        
        
        Generico1<Double, Integer> generico1= new Generico1(prec, stock);
        double resultado = generico1.multiplicar();
         if (datosValidos) {
             PMakeup pm = new PMakeup(namepro, cod , codpro, tipo, prec, stock, tonos, diri, fabri);
             makeupArray.agregarProductoM(pm);
             for (int i = 0; i < makeupArray.tamañoArreglo(); i++) {
                 Object[] fila={
                     makeupArray.obtener(i).getCodigo(),
                     makeupArray.obtener(i).getNombre_producto(),
                     makeupArray.obtener(i).getPrecio(),
                     makeupArray.obtener(i).getStock(),
                     makeupArray.obtener(i).getFabricado(),
                     makeupArray.obtener(i).getTipo(),
                     makeupArray.obtener(i).getTonos(),
                      makeupArray.obtener(i).getDirigidoPara(),
                     makeupArray.obtener(i).getCodproveedor(),
                     resultado
                     
                    
                 };
                 tMakeup.addRow(fila);
                 
             }
             //agregar datos a la BDD
            try {
                PreparedStatement pps=  cn.prepareStatement("INSERT INTO promakeup(Codigo,Nombreprod,Precio,Stock,Fabricados,Tipo,Tonos,DigPara,CodProv) VALUES(?,?,?,?,?,?,?,?,?)");
                pps.setInt(1, cod);
                pps.setString(2, namepro);
                pps.setDouble(3, prec);
                pps.setInt(4, stock);
                pps.setString(5, fabri);
                pps.setString(6, tipo);
                pps.setString(7, tonos);
                pps.setString(8, diri);
                pps.setInt(9, codpro);
                pps.executeUpdate();
                JOptionPane.showMessageDialog(null, "Producto Guardado");
            } catch (SQLException ex) {
                Logger.getLogger(FrameProductos.class.getName()).log(Level.SEVERE, null, ex);
            }
        } 
        
        }  
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        
        DefaultTableModel model = (DefaultTableModel) tblMakeup.getModel();
        if(tblMakeup.getSelectedRowCount()== 1){
            model.removeRow(tblMakeup.getSelectedRow());
            
        }else{
            if(tblMakeup.getRowCount()== 0){
                JOptionPane.showMessageDialog(null,"La tabla esta vacía");
                           
            }else{ 
                JOptionPane.showMessageDialog(null, "Debe seleccionar una fila");
            }
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        txtCod3.setText("");
        txtCodPro3.setText("");
        txtNamePro3.setText("");
        txtPrecio3.setText("");
        txtStock3.setText("");
        txtdiri3.setText("");
        txttonos3.setText("");
        txttipo3.setText("");
    }//GEN-LAST:event_jButton12ActionPerformed

    private void txtCodKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodKeyTyped

        
        if (txtCod.getText().length()>=6)
        {
            evt.consume();
        } 
    }//GEN-LAST:event_txtCodKeyTyped

    private void txtNameProKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameProKeyTyped
        
    }//GEN-LAST:event_txtNameProKeyTyped

    private void txtcontenidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcontenidoKeyTyped
        
    }//GEN-LAST:event_txtcontenidoKeyTyped

    private void txtcontenidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcontenidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcontenidoActionPerformed

    private void txtCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodActionPerformed

    private void txtCodProKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodProKeyTyped

        //maximo de digitos
        if (txtCodPro.getText().length()>=6)
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtCodProKeyTyped

    private void txtStockKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStockKeyTyped
        Character c = evt.getKeyChar();
    if(!Character.isDigit(c))
        evt.consume();
    }//GEN-LAST:event_txtStockKeyTyped

    private void cmbtipfabriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbtipfabriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbtipfabriActionPerformed

    private void txtCod2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCod2KeyTyped
  
        
        if (txtCod2.getText().length()>=6)
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtCod2KeyTyped

    private void txtCodPro2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodPro2KeyTyped

        if (txtCodPro2.getText().length()>=6)
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtCodPro2KeyTyped

    private void txtCod3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCod3KeyTyped

        //maximo de digitos
        if (txtCod3.getText().length()>=6)
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtCod3KeyTyped

    private void txtCodPro3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodPro3KeyTyped
  
        if (txtCodPro3.getText().length()>=6)
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtCodPro3KeyTyped
    
    private void txtStock3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStock3KeyTyped
        Character c = evt.getKeyChar();
    if(!Character.isDigit(c))
        evt.consume();
    }//GEN-LAST:event_txtStock3KeyTyped

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        cerrar();
        
    }//GEN-LAST:event_formWindowClosing

    private void txtPrecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioKeyTyped

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
   FramePrincipal abrir = new FramePrincipal();
   abrir.setVisible(true);
   this.setVisible(false);              // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
     FramePrincipal abrir = new FramePrincipal();
   abrir.setVisible(true);
   this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
    FramePrincipal abrir = new FramePrincipal();
   abrir.setVisible(true);
   this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void txttonos3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttonos3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttonos3ActionPerformed
    
    private void cerrar(){
        //Noveno
        //Creamos un cuadro de mensaje para cerrar el formulario
        String bot[]={"Cerrar", "Cancelar"};
        int eleccion=JOptionPane.showOptionDialog(this, "¿Cerrar?", "Titulo", 0, 0, null, bot, this);
        if (eleccion==JOptionPane.YES_OPTION){
            System.exit(0);}
            else if (eleccion==JOptionPane.NO_OPTION){
                    System.out.println(DO_NOTHING_ON_CLOSE);
                    }
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameProductos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbTipocomes;
    private javax.swing.JComboBox<String> cmbtipfabri;
    private javax.swing.JComboBox<String> cmbtipfabri3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTable tblComida;
    private javax.swing.JTable tblHigiene;
    private javax.swing.JTable tblMakeup;
    private javax.swing.JTextField txtCod;
    private javax.swing.JTextField txtCod2;
    private javax.swing.JTextField txtCod3;
    private javax.swing.JTextField txtCodPro;
    private javax.swing.JTextField txtCodPro2;
    private javax.swing.JTextField txtCodPro3;
    private javax.swing.JTextField txtNamePro;
    private javax.swing.JTextField txtNamePro2;
    private javax.swing.JTextField txtNamePro3;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtPrecio2;
    private javax.swing.JTextField txtPrecio3;
    private javax.swing.JTextField txtStock;
    private javax.swing.JTextField txtStock2;
    private javax.swing.JTextField txtStock3;
    private javax.swing.JTextField txtcaducidad1;
    private javax.swing.JTextField txtcontenido;
    private javax.swing.JTextField txtdiri3;
    private javax.swing.JTextField txttipo;
    private javax.swing.JTextField txttipo3;
    private javax.swing.JTextField txttonos3;
    // End of variables declaration//GEN-END:variables

    

}
